### ISSUE TITLE
Issue if CSV have number like 1234,56

### ISSUE THREAD

**Issue by Escalion86** [khaeransori/vscode-json2csv#9]
Issue if CSV have number like 1234,56

For example in CSV: "0,00",,"0,00",,"",  ....
Because number have ","

**Comment by khaeransori** [comment]
Hi @Escalion86 ,

Thank you for reporting this issue back in 2020.

I’ve reviewed the issue regarding numbers with commas in CSV (e.g., 1234,56), and after thorough testing, I’m unable to reproduce the problem in the current version (1.0.0). It seems that the handling of commas and number formatting has been addressed since the original report.
